apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-k8s
  labels:
    app: hello-k8s

spec:
  replicas: 3

  selector:
    matchLabels:
      app: hello-k8s

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - name: hello-k8s
          image: hello-k8s:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: hello-k8s-config
                  key: APP_MESSAGE

            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: hello-k8s-config
                  key: APP_ENV

      volumes:
        - name: config-volume
          configMap:
            name: hello-k8s-config-v2
