apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: hello-k8s
  labels:
    app: hello-k8s

spec:
  replicas: 3

  selector:
    matchLabels:
      app: hello-k8s

  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - name: hello-k8s
          image: hello-k8s:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
